### ISSUE TITLE
Config file for server or command edit

### ISSUE THREAD

**Issue by claudioneiserafini** [nonamecrackers2/ender-trigon#12]
Hi, 

I wanted to add in my modpack server but I'm trying problems with terrain destruction, I wish it had a config file or command to disable the **CRASH Attack** option.

FORGE 47.2.20
Version 1.20.1
Mod Version: 1.0

![enderdragon](https://github.com/nonamecrackers2/ender-trigon/assets/80057508/9f4f0d85-19f5-4ad4-8480-cdc168bbbe08)

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
