### ISSUE TITLE
Is this mod compatible with "True Ending: Ender Dragon Overhaul" mod?

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/ender-trigon#18]
**Minecraft Version**
1.20.1

**Mod version**
Latest

**Describe the bug**
Hi, i want to know if this mod is compatible with "True Ending: Ender Dragon Overhaul" mod. Cuz i see both of these mods add new mechanics to the Ender Dragon.

**Link to the other mod page**
https://modrinth.com/datapack/true-ending

**Comment by nonamecrackers2** [comment]
I haven't tried the two together so I am not sure. If you encounter any compatibility issues between the two, feel free to come here and open a bug report.

**Comment by ghost** [comment]
It works fine together, thanks for your work, ender trigon is amazing :)

**Comment by nonamecrackers2** [comment]
Thanks! I'm glad they work together, thanks for testing
