### ISSUE TITLE
Compatibility issue with Savage Ender Dragon Mod

### ISSUE THREAD

**Issue by VanillaSnowGolem** [nonamecrackers2/ender-trigon#6]
**Minecraft version**
1.19.4

**Mod version**
1.0

**Describe the bug**
Can't open the game, most likely due to clashing between Ender Trigon and Savage Ender Dragon, especially since the latter has player amount scaling.

**To Reproduce**
1. put the two mods in the mod folder
2. try to launch the game
3. game crashes with Exit Code: 1

**Crash Reports / Logs**
No crash report, don't know what to do about that

**Screenshots**
No screenshot needed either I don't think

**Comment by nonamecrackers2** [comment]
Just tried it with the recommended and latest Forge version, wasn't able to reproduce. This is quite late so you may have solved it already, but try a newer savage ender dragon version.
