### ISSUE TITLE
Crash in newer forge version (1.20.1)

### ISSUE THREAD

**Issue by Rozarke** [nonamecrackers2/ender-trigon#7]
**Minecraft version**
1.20.1

**Mod version**
latest for 1.20.1

**Describe the bug**
crash when enter in end dimension in forge 47.1.6, older version work

**To Reproduce**
just go in end dimension in new version of forge

**Crash Reports / Logs**
https://pastebin.com/pxUpvBfg

**Screenshots**
not needed

**Comment by nonamecrackers2** [comment]
Sorry this is quite late, just tried out with the latest Forge version (47.1.43) and this issue has been fixed.
